export * from "./router-params"
export * from "./http-word.type"
export * from "./router.decorator"
export * from "./router-words-decortors"
export * from "./registrable-route-properties.interface"
export * from "./router-setup.strategy"
