export const CONTROLLERS_TO_SET_UP_METADATA_KEY = "CONTROLLERS_TO_SET_UP_METADATA_KEY"
export const REGISTRABLE_PROPERTIES_METADATA_KEY =
  "REGISTRABLE_PROPERTIES_METADATA_KEY"
export const REGISTRABLE_ROUTES_METADATA_KEY = "REGISTRABLE_ROUTES_METADATA_KEY"
export const ARGUMENTS_METADATA_KEY = "ARGUMENTS_METADATA_KEY"
export const ROUTES_TO_SET_UP = "ROUTES_TO_SET_UP"
export const ROUTER_CONFIG = "ROUTER_CONFIG"
export const COMMANDS_TO_SET_UP = "COMMANDS_TO_SET_UP"
export const REGISTRABLE_COMMANDS_METADATA_KEY = "REGISTRABLE_COMMANDS_METADATA_KEY"
